# config/app.yml for rails-settings-cached
#
# This file contains default values, and does not need to be edited
# when configuring an instance.  These settings may be changed by an
# Administrator using the Web UI.
#
# For more information, see docs/Running-Mastodon/Administration-guide.md
#
defaults: &defaults
  site_title: '艦ます'
  site_description: '「艦ます」は提督のためのSNSです。プレイ実況や攻略情報の共有、ほか艦これの雑談にご利用ください。'
  site_extended_description: ''
  site_contact_username: 'admin'
  site_contact_email: 'kancolle.mastodon@gmail.com'
  open_registrations: true
  closed_registrations_message: ''
  boost_modal: false
  auto_play_gif: true
  notification_emails:
    follow: false
    reblog: false
    favourite: false
    mention: false
    follow_request: true
    digest: false
  interactions:
    must_be_follower: false
    must_be_following: false

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
